version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: spezzz/foodgram:v.01
#    build:
#      context: ../backend/foodgram
#      dockerfile: Dockerfile
    restart: always
    volumes:
#      - static_value:/app/static_backend/
      - static_value:/app/static/
      - media_value:/app/media/
#      - scripts:/app/scripts/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: spezzz/foodgram-frontend:v.01
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
#      - static_value:/app/result_build/build/static/
#    env_file:
#      - ./.env
#    depends_on:
#      - backend

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
#      - static_value:/var/html/static_backend/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
