version: '3.7'

services:
  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: spezzz/foodgram_backend:latest
#    build:
#      context: ../backend/foodgram
#      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    image: spezzz/foodgram_frontend:latest
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
      - static_value:/app/result_build/build/static/
    env_file:
      - ./.env
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
